#Amazon AWS Config
development:
  access_key_id: **********
  secret_access_key: **************
  bucket: ****

production:
  access_key_id: AKIAJSK7KUXWSNLGW36Q
  secret_access_key: 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
  bucket: bucketmizikjams
  
  
  


   

